server:
  port: 6005
  


spring:
    application: 
     name: microservicecloud-config-github
    datasource: 
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/springcloud_cooperation
     username: root
     password: 123
     dbcp2: 
      min-idle: 50
      initial-size: 50
      max-total: 50
      max-wait-millis: 2001
      
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
